import Link from "next/link";
import { db } from "@/db/db";
import { authorizedAdmins, businessSettings } from "@/db/schema";
import { requireAdmin } from "@/lib/admin-auth";
import { getGoogleConnection } from "@/lib/gmail";
import { AdminTopbar } from "../_components/admin-topbar";
import { addAuthorizedUser, disableAuthorizedUser, removeAuthorizedUser, saveBusinessSettings } from "../admin-users-actions";
import { disconnectGoogle } from "../gmail-actions";

export default async function SettingsPage() {
  const session = await requireAdmin();
  const [settings] = await db.select().from(businessSettings).limit(1);
  const users = await db.select().from(authorizedAdmins).orderBy(authorizedAdmins.createdAt);
  const connection = await getGoogleConnection(session.adminId);
  return <><AdminTopbar title="Settings" description="Business profile, Gmail connection, and authorized admin users." />
  <div className="grid gap-5"><section className="rounded-[1.5rem] border border-white/10 bg-[rgba(36,35,35,0.5)] p-6"><h2 className="font-display text-lg font-semibold">Business Profile</h2><form action={saveBusinessSettings} className="mt-4 grid gap-3 md:grid-cols-2">{[["businessName","Business name",settings?.businessName],["businessEmail","Business email",settings?.businessEmail],["phone","Phone",settings?.phone],["logoUrl","Logo",settings?.logoUrl],["address","Address",settings?.address]].map(([n,l,v])=><label key={n} className="text-sm text-muted-foreground">{l}<input name={n} defaultValue={v || ""} className="mt-1 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-foreground" /></label>)}<button className="rounded-full bg-blue-600 px-5 py-2 text-sm font-semibold text-white md:col-span-2">Save profile</button></form></section>
  <section className="rounded-[1.5rem] border border-white/10 bg-[rgba(36,35,35,0.5)] p-6"><h2 className="font-display text-lg font-semibold">Google Connection</h2><div className="mt-3 grid gap-2 text-sm text-muted-foreground"><p>Connected Google account: <span className="text-foreground">{connection?.googleEmail || "Not connected"}</span></p><p>Gmail API status: <span className={connection && !connection.revokedAt ? "text-green-300" : "text-red-300"}>{connection && !connection.revokedAt ? "Connected" : "Disconnected"}</span></p></div><div className="mt-5 flex gap-2"><Link href="/api/auth/google" className="rounded-full bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Reconnect</Link><form action={disconnectGoogle}><button className="rounded-full border border-white/10 px-4 py-2 text-sm">Disconnect</button></form></div></section>
  <section className="rounded-[1.5rem] border border-white/10 bg-[rgba(36,35,35,0.5)] p-6"><h2 className="font-display text-lg font-semibold">Authorized Users</h2>{session.role === "SUPER_ADMIN" && <form action={addAuthorizedUser} className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_160px_auto]"><input name="name" placeholder="Name" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2"/><input name="email" type="email" placeholder="Google email" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2"/><select name="role" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2"><option>ADMIN</option><option>SUPER_ADMIN</option></select><button className="rounded-full bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Add</button></form>}<div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-muted-foreground"><tr><th className="py-2">Name</th><th>Email</th><th>Role</th><th>Status</th><th></th></tr></thead><tbody>{users.map((u)=><tr key={u.id} className="border-t border-white/10"><td className="py-3">{u.name}</td><td>{u.googleEmail}</td><td>{u.role}</td><td>{u.active ? "Active" : "Disabled"}</td><td className="flex gap-2 py-2">{session.role === "SUPER_ADMIN" && <><form action={async()=>{"use server"; await disableAuthorizedUser(u.id)}}><button className="text-amber-300">Disable</button></form><form action={async()=>{"use server"; await removeAuthorizedUser(u.id)}}><button className="text-red-300">Remove</button></form></>}</td></tr>)}</tbody></table></div></section></div></>;
}
