import { Portfolio } from "./types";

export const portfolioData: Portfolio[] = [
  {
    id: "p1",
    title: "Estate Water Supply — Trasacco Valley",
    location: "Trasacco Valley, Accra",
    region: "Greater Accra",
    service: "Borehole Drilling",
    depth: "180ft",
    yieldRate: "1,800 L/hr",
    duration: "3 days",
    year: "2025",
    img: "/images/home/borehole-drilling.jpeg",
    summary:
      "A single borehole feeding a six-unit residential estate. Survey confirmed a strong sedimentary aquifer at 180ft, giving enough yield to serve all six homes off one source.",
    status: "published",
    featured: true,
    createdAt: "2025-03-14",
  },
  {
    id: "p2",
    title: "Community Well Rehabilitation — Tamale",
    location: "Tamale, Northern Region",
    region: "Northern",
    service: "Borehole Rehabilitation",
    depth: "220ft",
    yieldRate: "900 → 1,600 L/hr",
    duration: "2 days",
    year: "2024",
    img: "/images/home/borehole-rehabilitation.png",
    isVideo: true,
    summary:
      "A 12-year-old community borehole had dropped to a trickle. Re-developed the hole and cleared accumulated silt, nearly doubling yield without a full re-drill.",
    status: "published",
    featured: false,
    createdAt: "2024-08-02",
  },
  {
    id: "p3",
    title: "School Water Project — Kumasi",
    location: "Kumasi, Ashanti Region",
    region: "Ashanti",
    service: "Hydro-fracturing",
    depth: "310ft",
    yieldRate: "2,400 L/hr",
    duration: "5 days",
    year: "2024",
    img: "/images/home/hydro-fracturing.png",
    summary:
      "Initial drilling into hard basement rock returned a weak yield. Hydro-fracturing opened up fracture zones in the surrounding rock, lifting output enough to supply the entire school compound.",
    status: "published",
    featured: true,
    createdAt: "2024-05-19",
  },
  {
    id: "p4",
    title: "Farm Irrigation Borehole — Techiman",
    location: "Techiman, Bono Region",
    region: "Ashanti",
    service: "Borehole Drilling",
    depth: "260ft",
    yieldRate: "3,100 L/hr",
    duration: "4 days",
    year: "2023",
    img: "/images/home/pumping-tests.png",
    summary:
      "A 15-acre commercial farm needed year-round irrigation capacity. Survey and pumping test confirmed a high-yield source, paired with a solar pump sized for peak dry-season demand.",
    status: "published",
    featured: false,
    createdAt: "2023-11-27",
  },
  {
    id: "p5",
    title: "Church Compound Supply — Takoradi",
    location: "Takoradi, Western Region",
    region: "Western",
    service: "Pump Installation",
    depth: "195ft",
    yieldRate: "1,500 L/hr",
    duration: "1 day",
    year: "2023",
    img: "/images/home/pump-installation.png",
    summary:
      "Existing borehole had never had a properly sized pump installed. Fitted and tested a submersible pump matched to the actual yield, ending years of inconsistent pressure.",
    status: "published",
    featured: false,
    createdAt: "2023-06-09",
  },
  {
    id: "p6",
    title: "Residential Site Survey — East Legon",
    location: "East Legon, Accra",
    region: "Greater Accra",
    service: "Geological Surveys",
    depth: "N/A",
    yieldRate: "N/A",
    duration: "Half day",
    year: "2025",
    img: "/images/home/geological-surveys.png",
    summary:
      "A pre-purchase land survey to confirm groundwater viability before the client committed to buying the plot. Confirmed depth and expected yield ahead of any construction.",
    status: "draft",
    featured: false,
    createdAt: "2025-01-22",
  },
  {
    id: "p7",
    title: "Hospital Backup Water Source — Koforidua",
    location: "Koforidua, Eastern Region",
    region: "Eastern",
    service: "Air Lifting / Developing of Borehole",
    depth: "240ft",
    yieldRate: "2,000 L/hr",
    duration: "4 days",
    year: "2022",
    img: "/images/home/air-lifting.png",
    isVideo: true,
    summary:
      "A district hospital needed a reliable backup source independent of municipal supply interruptions. After drilling, we air-lifted and fully developed the hole to clear debris and open it to its actual yield before handover.",
    status: "published",
    featured: false,
    createdAt: "2022-09-30",
  },
  {
    id: "p8",
    title: "Hotel Facility Rehabilitation — Cape Coast",
    location: "Cape Coast, Central Region",
    region: "Central",
    service: "Borehole Rehabilitation",
    depth: "205ft",
    yieldRate: "700 → 1,900 L/hr",
    duration: "3 days",
    year: "2022",
    img: "/images/home/borehole-rehabilitation.png",
    summary:
      "A resort's original borehole was drilled decades earlier with no casing record. Redeveloped and re-cased the hole, restoring supply ahead of peak tourist season.",
    status: "published",
    featured: false,
    createdAt: "2022-04-11",
  },
  {
    id: "p9",
    title: "Yield Verification — Sunyani",
    location: "Sunyani, Bono Region",
    region: "Ashanti",
    service: "Pumping Tests",
    depth: "230ft",
    yieldRate: "1,700 L/hr sustained",
    duration: "1 day",
    year: "2023",
    img: "/images/home/pumping-tests.png",
    summary:
      "An existing borehole needed its sustainable yield confirmed before the client committed to a large-capacity pump. A full pumping test set the safe long-term draw rate, avoiding an oversized (and overpriced) pump.",
    status: "published",
    featured: false,
    createdAt: "2023-02-17",
  },
];
