"use client";
import { useState } from "react";
import { FaEnvelopeOpenText, FaCopy, FaExternalLinkAlt, FaCheck } from "react-icons/fa";
import { GmailListItem, gmailReplyUrl } from "@/lib/gmail-client";
import { markHandled } from "../gmail-actions";

export function GmailRequestList({ messages }: { messages: GmailListItem[] }) {
  const [selected, setSelected] = useState<GmailListItem | null>(messages[0] ?? null);
  if (!messages.length) return <div className="rounded-[1.5rem] border border-white/10 bg-[rgba(36,35,35,0.5)] p-8 text-center text-muted-foreground">No matching Gmail messages found.</div>;
  return <div className="grid gap-5 lg:grid-cols-[1fr_0.9fr]"> <div className="space-y-3">{messages.map((m)=><button key={m.id} onClick={()=>setSelected(m)} className="w-full rounded-[1.2rem] border border-white/10 bg-[rgba(36,35,35,0.5)] p-4 text-left hover:border-blue-500/40"><div className="flex justify-between gap-3"><div><p className="font-semibold text-foreground">{m.fromName || m.fromEmail}</p><p className="text-xs text-muted-foreground">{m.fromEmail}</p></div><span className="text-xs text-muted-foreground">{m.date ? new Date(m.date).toLocaleString() : ""}</span></div><p className="mt-3 text-sm font-medium text-foreground">{m.unread ? "• " : ""}{m.subject}</p><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{m.preview}</p>{m.handled && <span className="mt-3 inline-flex rounded-full bg-green-500/10 px-2.5 py-1 text-xs text-green-300">Handled</span>}</button>)}</div>{selected && <aside className="rounded-[1.5rem] border border-white/10 bg-[rgba(36,35,35,0.5)] p-6"><FaEnvelopeOpenText className="text-blue-500"/><h2 className="mt-4 font-display text-xl font-semibold">{selected.subject}</h2><p className="mt-2 text-sm text-muted-foreground">From {selected.fromName} &lt;{selected.fromEmail}&gt;</p><p className="mt-5 whitespace-pre-wrap rounded-xl bg-black/20 p-4 text-sm text-muted-foreground">{selected.preview}</p><div className="mt-5 flex flex-wrap gap-2"><a target="_blank" href={gmailReplyUrl(selected)} className="rounded-full bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Reply in Gmail <FaExternalLinkAlt className="ml-2 inline h-3 w-3"/></a><button onClick={()=>navigator.clipboard.writeText(selected.fromEmail)} className="rounded-full border border-white/10 px-4 py-2 text-sm"><FaCopy className="mr-2 inline h-3 w-3"/>Copy email</button><form action={async()=>{await markHandled(selected.id)}}><button className="rounded-full border border-white/10 px-4 py-2 text-sm"><FaCheck className="mr-2 inline h-3 w-3"/>Mark handled</button></form></div></aside>}</div>;
}
